sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-127
env:
  global:
    -
      # LTD_AWS_ID
      secure: FWw2EItOucwLaFaPMUtHREq3N65veKzvvQVpRm0r3p5P8zqdeZBuK0N9a4ey04PwJ637469e2hkCCIxwRjUOXp1cqZJA8KkDxy2IJtNzCtlmk00EaRG+Vg61QEmMfhhJYmym+bUZ9rsS5PxJ0FlKReP2mGwxFLvjAIi3NEudaqMNPGeHQV3F7JfINwC+hq2FaB9y86i8540TWSOdKbdzmS8anmrQYaZkr1KFVjHn+GFNUYI1ZeQnCmQGFLmt1OlbyL59UlpRHJ3pKQy5iK48/8O/6CUuBJfJk44TpgjXXDrunswVoPWKIwEDfAe6FNKBP9hDpshAufgi+LC65pIdo7eMN7giCSZmMdC3JBnucUaeXhRL+nwHYeN3BPsrjn1axTtOvJCy8r08h7iNdNB56vfI/5Hm0lxUX9Cpix4WB/rvaFsEjXhGvWBNhoUgE1mdTZnVFYsWFAiYJoO/Hf7lqBLd9W1CEh6wof9lftQmcKgmMrO9YStEr025/VFIkRyweMssQdISZESxB6/IimVCl0Pt4V7cNXSw25lmc8n1zFOOF6QMEgOnRAE0p7h4PPTyNOYG2SxtOjKqb0YbuwF8qWLgFJBaGpUQDZgvdRNnthNS8NfNw5fmpXiMO/wnuQUJYcBnHIzSwTyUPRD9ptfzMTfK3dVZq8Pe8U9golF8Y7w=
    -
      # LTD_AWS_SECRET
      secure: Bit5nSGji4m2b1oG1YinpHAf9XwjCOBn4PrBrB+me+JTj1CCCqbSAldoHb31se+eeQX29dWprkgPetOWnXhTSrugc20yXYqbfc1cdaXZYXGEceOXmFIQtmxE/zRnqdeQ2P/sLdUEpuiPnqdRT+hlM4BxhYyQUzvNhKBLLDSTuuz1BX/LX5Ecd+RV3f+5ppycukf0qPAN/QyOhKbLjgeKwYiNH+gdeRI9L9cHHWA5y6PuOWzi7HlhYTvpZXRMrc7YlaFqWcquoV539vGclRjbNpfghTbMERSZpyT/f5JRQl17Rvu3TWfru/XhiniR8T3P9Sz72sCThyzoxcqzmVkJxqAZdysa9eXLmnO0WMnsCmXLR3uVK1L5OM3kF+fMyYyGiIdQ2IJMHj9vZVGQXBEskqX88mRfOWbbgBT9drBL8Aj2zZYJcgXUAdEb4GSHG314vauFcYtTMnP+S2/jEHDzBrRzeEdp+/wVyUdsZI1QbtDbH5K3mm3hzrJ/vqUZYgaUYbgmYoV13Tcm3qqSNXBoBTVmVfdzh/kahTd/2HNhFiVAduw2exCr4YEN3p+NzRAY9tWKdkIsB49gP2KrPmgbQRd3NJlz+E7LoFK48Po4AkhzG8GKSLwo5eywmJGHcJrHI7myutORIzWB10a0e+OvvC/M2FIoF9Ba48EWKXLWeiA=
    -
      # LTD_USERNAME
      secure: I3f5A4I75OKBJ04UBgH1xX30wCUITqJbzJEQivmAbkDNolIne1RVV/SN5sLGHCI4Wv54PwUFcGZhT9u2KzihOs1Kf1VQ8R0B2XvT1ifZBgmzQfjSUg7PDcUPD0tCWMdQ6k8+rlFPnDWF4Aona6kw1yO+eNPFwL1CfWUCr9wpIW377oYyibYy/Yr8/OTc54CV31a+vmxpSBzj3FKBWAThyDMWGGnlo5JEPD/9u9NK3+J7EAVIIq2VsJQDWrkfNorw/fbTTkJMko1JVhu/3qENJ/xU+rKlHB51cZiNvWRTX4URVeIn5DQ3mi9TcAGz9ghXjBxOCqZdxmsWwDKrOqJ0vFfOTIfTQyYgl+19olUPqG1eMAQPkPxBELw0xgSAN0q0uIzbrzp8w1g8r/TUNBJnex0qIqeebZqIGbqZbhVAtQKRst1IuYaJ09wIsBI+4Q7mIJSRcJcHqaSlNWlPBaIqwUCfIKmgysRYSDDtHXRARRPxuw6jLE/coxV+ralcxTZGZEqROorheetxOmGOTmTgTsn924pNwLLOoXiDiB/oUDlOchLNYUiUc9DdhChztbIduo/0cfQ3A5/CAMDG3RJwfGyX6JWLDX8SoYRTFE86OBwjjTY3Avst+/muGlhLMFZ1UgdfD1Iukk5tJxoyMz+sVnjpCvgaHozxOrEEhfsmwgY=
    -
      # LTD_PASSWORD
      secure: YZ3MD8ui4QV5oglzalkh34i+wNgC34iww4THEvtwMQ2G/JD6Cs6pR+F5vNz/uX9Y2JOsdhw+x09ZO5F+N4woDsU00SQXKgHRP3W+T2cG2wMtMwgHqcT6Eb3PfPzOAhrnrBlYSYFLSW+K6CvxC3iOsGp6JbUUkrYqLIGUNwY641BTIJbs9QMdS1TS6Sv+kbJpVkNxd1M6ol+X49nq59ZWUwiv8PaizqN2T+aZzMWchcWn8w7puSy/nkF2RrEvAtS+HyCq5HYzvvjEl8piJi8AxeS+85qURiLOiRgFc7jmMyhsx3eif6sruh/DxzfOtTOJaCEzgpW1EOz27AVwp00Szh8EHhKEfOY/h+lzTcncjl2ehwAC2FCHqxKhxY+lJPlX/Ef6XbscKxoW+wu5tbg1HN0ZyxKcPt05tQXp/+/u8VgkILxt/r2iok/qrNfDwu//PCLY70a3Sgj2dm4culFrdsJXVlKml0TrIT2o23H05aJc2lAK083uwzan2feqwILZKebNlpAvo5QyBROe6Ys449lSdDLv9VE5PY1tx11pvKYlMqgUHOElRlyS4RXGmIogc+zGhokXDey0adCst4rulP8KNc6gGEkj4BxsFweQ6rZfcil+f5wMFDXythlwq+oK3uCXYFT+H/qWZxCh5RpspRUxuWWcHwXz/UWKyrWK1Lg=
